### ISSUE TITLE
带你玩转PyOne：onedrive列表工具（一、安装篇） — 一个人的公交

### ISSUE THREAD

**Issue by abbeyokgo** [abbeyokgo/abbeyokgo.github.io#3]
https://abbeyokgo.github.io/2018/08/16/pyone-onedrive-part1/ 

 PyOne介绍  onedrive列表程序，可用于更好的分享文件  基于Flask开发，Python是最好的语言demo展示：http://3pp.me （别问我密码）

**Comment by abbeyokgo** [comment]
如果有任何问题，请及时提问

**Comment by zaaard** [comment]
### 下载文件时页面出现
Internal Server Error  

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.  

### ssh显示这个
[2018-09-01 19:07:21,984] ERROR in app: Exception on /file/01KZDKAL3V5HMPYZ3QVVG2CGWC6S4NPCRZ [POST]  
Traceback (most recent call last):  
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()  
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)  
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)  
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()  
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)  
  File "/www/wwwroot/yys.tw/run.py", line 277, in show
    return render_template('show/any.html',content=content)  
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)  
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)  
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)  
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)  
  File "/www/wwwroot/yys.tw/templates/show/any.html", line 1, in top-level template code
    {%extends 'layout.html'%}  
  File "/www/wwwroot/yys.tw/templates/layout.html", line 34, in top-level template code
    {%block content%}  
  File "/www/wwwroot/yys.tw/templates/show/any.html", line 4, in block "content"
    {{content}}  
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 11: invalid start byte  
不知道是我nignx配置的问题还是获取下载链接时出错。。

**Comment by abbeyokgo** [comment]
> @zaaard
> ### 下载文件时页面出现
> Internal Server Error  
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.  
> 
> ### ssh显示这个
> [2018-09-01 19:07:21,984] ERROR in app: Exception on /file/01KZDKAL3V5HMPYZ3QVVG2CGWC6S4NPCRZ [POST]  
> Traceback (most recent call last):  
>   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()  
>   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)  
>   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)  
>   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()  
>   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)  
>   File "/www/wwwroot/yys.tw/run.py", line 277, in show
>     return render_template('show/any.html',content=content)  
>   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 135, in render_template
>     context, ctx.app)  
>   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 117, in _render
>     rv = template.render(context)  
>   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)  
>   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)  
>   File "/www/wwwroot/yys.tw/templates/show/any.html", line 1, in top-level template code
>     {%extends 'layout.html'%}  
>   File "/www/wwwroot/yys.tw/templates/layout.html", line 34, in top-level template code
>     {%block content%}  
>   File "/www/wwwroot/yys.tw/templates/show/any.html", line 4, in block "content"
>     {{content}}  
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 11: invalid start byte  
> 不知道是我nignx配置的问题还是获取下载链接时出错。。
> 

留个联系方式，我估计是什么bug，反正是Python编码问题，我帮你调试一下

**Comment by zaaard** [comment]
> @abbeyokgo
> 留个联系方式，我估计是什么bug，反正是Python编码问题，我帮你调试一下  

企鹅：1026643210  
telegram：https://t.me/loli520

**Comment by liukewei8911** [comment]
想问一下这个情况怎么解决 一直无法更新数据 谢谢

getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :2, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :3, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :4, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?

**Comment by abbeyokgo** [comment]
> @liukewei8911
> 想问一下这个情况怎么解决 一直无法更新数据 谢谢
> 
> getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :2, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
> getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :3, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
> getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :4, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?

自己检查app_url，少了一个/，直接修改data/AppUrl的网址

**Comment by liukewei8911** [comment]
> @abbeyokgo
> > @liukewei8911
> > 想问一下这个情况怎么解决 一直无法更新数据 谢谢
> > 
> > getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> > error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :2, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
> > getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> > error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :3, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
> > getting files from url https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails
> > error to opreate GetItem("https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails","0",""),try times :4, reason: Invalid URL u'https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails': No schema supplied. Perhaps you meant http://https:/dutaotbsteduau-my.sharepoint.com/_api/v2.0/me/drive/root/children?expand=thumbnails?
> 
> 自己检查app_url，少了一个/，直接修改data/AppUrl的网址

好了 谢谢 以为只用改config.py里面的

**Comment by Creling** [comment]
博主，想请教一下，在VPS的shell界面是这样的，似乎是安装正确了
![](https://images.fromling.xyz/upload/1809/57dda5dd9ddf83d7.png)
但是网页总数卡在“正在更新数据”请问要如何解决?

**Comment by abbeyokgo** [comment]
> @Creling
> 博主，想请教一下，在VPS的shell界面是这样的，似乎是安装正确了
> ![](https://images.fromling.xyz/upload/1809/dc4accef0fb4bc32.png)
> 但是网页总数卡在“正在更新数据”请问要如何解决?
> 

结束运行，手工运行命令更新数据

**Comment by Creling** [comment]
> @abbeyokgo
> > @Creling
> > 博主，想请教一下，在VPS的shell界面是这样的，似乎是安装正确了
> > ![](https://images.fromling.xyz/upload/1809/dc4accef0fb4bc32.png)
> > 但是网页总数卡在“正在更新数据”请问要如何解决?
> > 
> 
> 结束运行，手工运行命令更新数据

手动更新数据？具体是执行什么命令？似乎没有找到相关的说明

**Comment by abbeyokgo** [comment]
> @Creling
> > @abbeyokgo
> > > @Creling
> > > 博主，想请教一下，在VPS的shell界面是这样的，似乎是安装正确了
> > > ![](https://images.fromling.xyz/upload/1809/dc4accef0fb4bc32.png)
> > > 但是网页总数卡在“正在更新数据”请问要如何解决?
> > > 
> > 
> > 结束运行，手工运行命令更新数据
> 
> 手动更新数据？具体是执行什么命令？似乎没有找到相关的说明

https://abbeyok.com/2018/08/16/pyone-onedrive-part2/

**Comment by Creling** [comment]
> @abbeyokgo
> > @Creling
> > > @abbeyokgo
> > > > @Creling
> > > > 博主，想请教一下，在VPS的shell界面是这样的，似乎是安装正确了
> > > > ![](https://images.fromling.xyz/upload/1809/dc4accef0fb4bc32.png)
> > > > 但是网页总数卡在“正在更新数据”请问要如何解决?
> > > > 
> > > 
> > > 结束运行，手工运行命令更新数据
> > 
> > 手动更新数据？具体是执行什么命令？似乎没有找到相关的说明
> 
> https://abbeyok.com/2018/08/16/pyone-onedrive-part2/

谢谢，问题解决了，但是还有一个问题想要请教一下：
当我使用域名打开pyone时，下载压缩包等文件一切正常，但是预览文件（包括图片和视频时），无法预览，无法下载。并且页面里下载链接为 https：//127.0.0.1：34567/file/*************************
当我用ip地址打开pyone时，一切正常，但是下载链接为https：//IP：34567/file/*************************

我该如何设置，才能够在我分享下载链接时显示为 https：//域名/****************？
